tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/services"
# Run your GitHub Actions locally
brew "act"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Modern, maintained replacement for ls
brew "eza"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# Configurable static site generator
brew "hugo"
# Interactive computing in Python
brew "ipython"
# Colorize your kubectl output
brew "kubecolor"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# YAML Parser
brew "libyaml"
# Run a Kubernetes cluster locally
brew "minikube"
# Object-relational database system
brew "postgresql@14"
# Persistent key-value database, with built-in net interface
brew "redis"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Maintained ctags implementation
brew "universal-ctags"
# Vi 'workalike' with many additional features
brew "vim"
# UNIX shell (command interpreter)
brew "zsh"
# Kubernetes CLI To Manage Your Clusters In Style!
brew "derailed/k9s/k9s"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# App to build and share containerised applications and microservices
cask "docker"
# Web browser
cask "google-chrome"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Clipboard manager
cask "maccy"
# App to write, plan, collaborate, and get organised
cask "notion"
# Collaboration platform for API development
cask "postman"
# To-do list
cask "todoist"
# Menu bar pomodoro timer
cask "tomatobar"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Native desktop client for WhatsApp
cask "whatsapp"
